name: deploy
on:
  pull_request:
    types: [closed]

jobs:
  deploy-web:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: deploy to ec2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/cicd-pipeline-workshop
            git pull
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm use 22.4.1
            /home/ubuntu/.nvm/versions/node/v22.4.1/bin/pm2 restart src/server.js
