name: deploy
on:
  pull_request:
    types: [closed]

jobs:
  deploy-web:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # - name: deploy to ec2
      # uses: appleboy/ssh-action@v1.0.3
      - run: echo "${{secrets.TEST}}"
